name: Check YAMLs

on:
  push:
    branches: [ "*" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
    - run: make -C specs check
