name: Checks

on:
  push:
    branches: [ "*" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
    - name: Validate YAMLs
      run: make -C specs check
    - name: Check python format
      run: uv run --dev ruff format --check python tests
    - name: Check python lint
      run: uv run --dev ruff check python tests
    - name: Run tests
      run: uv run --dev pytest --quiet
